# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64e78986cadc29d0c0355763ac61ec4e638b6eb4a359d9580f4e55dda8476eeb1f6f3e1515bacc7f82c0e558c79322a903d1e10327c3dc2983d95c8f81c7f40e

test:
  secret_key_base: 0c8d24b28de0d675b9d8e43f2973a59723640b179583e6c90aa450a153e8a1a059abcbe95a743aa7462df536dad372529b158bcb61c5b7dec5bdb3c3ddc80af1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
